services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo_oca:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-filestore:/var/lib/odoo/filestore
      - ./custom:/opt/odoo/custom
    environment:
      - ODOO_VERSION=17.0
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=odoo
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - ODOO_ADMIN_PASSWORD=admin
      - ODOO_EMAIL=admin@example.com
      - ODOO_DB=odoo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-filestore:
